version: 2

sources:
  - name: walmart
    database: OMNICHANNEL_DB
    schema: RAW
    tables:
      - name: walmart_sales

  - name: shopify
    database: OMNICHANNEL_DB
    schema: RAW
    tables:
      - name: shopify_orders
